apiVersion: v2
name: multicast-relay
description: Relay multicast and broadcast UDP packets between networks.
type: application
version: 0.1.4
appVersion: sha-8e5c648
keywords:
  - multicast
  - network
  - relay
