apiVersion: v2
name: multicast-relay
description: Relay multicast and broadcast UDP packets between networks.
type: application
version: 0.1.17
appVersion: 1.0.0
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source code
      url: https://github.com/Turgon37/multicast-relay
      icon: https://github.com/favicon.ico
    - name: Changelog
      url: https://github.com/Turgon37/multicast-relay/blob/master/CHANGELOG.md
    - name: Container package
      url: https://github.com/Turgon37/multicast-relay/pkgs/container/multicast-relay
  artifacthub.io/images: |
    - name: multicast-relay
      image: ghcr.io/turgon37/multicast-relay:1.0.0
  artifacthub.io/changes: |
    - kind: changed
      description: Add an option to receive multicast packets through UDP sockets instead of raw sockets.
      links:
        - name: Changelog
          url: https://github.com/Turgon37/multicast-relay/blob/master/CHANGELOG.md
    - kind: changed
      description: Expose the new receiveUdp relay option in the Helm chart values.
keywords:
  - multicast
  - network
  - relay
